name: build
on: [push]

defaults:
  run:
    working-directory: ./forge

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [16]    # Minimum supported by Minecraft
        # and run on both Linux and Windows
        #os: [ubuntu-20.04, windows-latest]
        os: [ubuntu-latest] # speed it up for now by only testing one
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle User Files
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-user-home
      - name: Cache Gradle Files
        uses: actions/cache@v1
        with:
          path: ./.gradle
          key: ${{ runner.os }}-gradle-file
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build --no-daemon -i --stacktrace
        env:
          GPR_USERNAME: ${{secrets.GPR_USERNAME}}
          GPR_TOKEN: ${{secrets.GPR_TOKEN}}
          GPR_BUILD_NUMBER: ${{github.run_number}}
      - name: capture build artifacts
        #if: ${{ runner.os == 'Linux' && matrix.java == '16' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/*.jar
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: publish
        run: ./gradlew publish
        env:
          GPR_USERNAME: ${{secrets.GPR_USERNAME}}
          GPR_TOKEN: ${{secrets.GPR_TOKEN}}
          GPR_BUILD_NUMBER: ${{github.run_number}}
